apiVersion: apps/v1
kind: Deployment
metadata:
  name: sglang-jiaying
  labels:
    k8s-app: sglang-jiaying
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: sglang-jiaying
  template:
    metadata:
      labels:
        k8s-app: sglang-jiaying
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      - NVIDIA-RTX-A6000
      containers:
      - name: mypod
        image: gitlab-registry.nrp-nautilus.io/stable-ucsd/sglang
        resources:
           limits:
             nvidia.com/rtxa6000: 1
             memory: 64Gi
             cpu: 8
           requests:
             nvidia.com/rtxa6000: 1
             memory: 64Gi
             cpu: 8
        volumeMounts:
        - mountPath: /mnt/data
          name: pvc-jiaying
        command: ["sh", "-c", "sleep infinity"]
      volumes:
      - name: pvc-jiaying
        persistentVolumeClaim:
          claimName: pvc-jiaying
      imagePullSecrets:
      - name: regcred 